version: '3.4'
services:
  # db:
  #   image: 'mcr.microsoft.com/mssql/server:2017-latest'
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: 'yourStrong(!)Password'
  #     ACCEPT_EULA: 'Y'
  worker:
    build:
      context: .
      target: builder
      args:
        NODE_ENV: 'development'
    command: 'npm run start:dev:worker'
    ports:
      - '3001:3001'
    environment:
      PORT: '3001'
      REDIS_URL: redis://redis:6379
    volumes:
      - ./:/app
  db:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - '6379:6379'
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
volumes:
  ? mysql
